// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuoteClient is the client API for Quote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuoteClient interface {
	GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error)
}

type quoteClient struct {
	cc grpc.ClientConnInterface
}

func NewQuoteClient(cc grpc.ClientConnInterface) QuoteClient {
	return &quoteClient{cc}
}

func (c *quoteClient) GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error) {
	out := new(GetQuoteResponse)
	err := c.cc.Invoke(ctx, "/quote.Quote/GetQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoteServer is the server API for Quote service.
// All implementations must embed UnimplementedQuoteServer
// for forward compatibility
type QuoteServer interface {
	GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error)
	mustEmbedUnimplementedQuoteServer()
}

// UnimplementedQuoteServer must be embedded to have forward compatible implementations.
type UnimplementedQuoteServer struct {
}

func (UnimplementedQuoteServer) GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedQuoteServer) mustEmbedUnimplementedQuoteServer() {}

// UnsafeQuoteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuoteServer will
// result in compilation errors.
type UnsafeQuoteServer interface {
	mustEmbedUnimplementedQuoteServer()
}

func RegisterQuoteServer(s grpc.ServiceRegistrar, srv QuoteServer) {
	s.RegisterService(&Quote_ServiceDesc, srv)
}

func _Quote_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quote.Quote/GetQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServer).GetQuote(ctx, req.(*GetQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Quote_ServiceDesc is the grpc.ServiceDesc for Quote service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Quote_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quote.Quote",
	HandlerType: (*QuoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuote",
			Handler:    _Quote_GetQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/quote.proto",
}
